export const DOC_TYPES =
	'.java, .cpp, .h, .cs, .rb, .swift, .kt, .php, .sql, .R, .pl, .scala, .rs, .dart, .lua, .m, .sh, .ps1, hs, .m, .cob, .cbl, .f, .f90, .adb, .ads, .scm, .pl, .erl, .d, .vhd, .v, .asm, .clj, .groovy, .dart, .kt, .js, .jsx, .vue, .ts, .tsx, .py, .html, .css, .json, .go, .txt, .xlsx, .csv, .doc, .docx, .pdf, .rtf, .odt, .png, .jpg, .jpeg, .svg, .webp';

export const DOC_TYPES_MAP = {
	devLangDocTypes: {
		java: 'java',
		cpp: 'cpp',
		h: 'h',
		cs: 'cs',
		graphql: 'graphql',
		rb: 'rb',
		swift: 'swift',
		kt: 'kt',
		php: 'php',
		sql: 'sql',
		R: 'R',
		pl: 'pl',
		scala: 'scala',
		rs: 'rs',
		dart: 'dart',
		lua: 'lua',
		m: 'm',
		sh: 'sh',
		ps1: 'ps1',
		hs: 'hs',
		cob: 'cob',
		cbl: 'cbl',
		f: 'f',
		f90: 'f90',
		adb: 'adb',
		ads: 'ads',
		scm: 'scm',
		pl: 'pl',
		erl: 'erl',
		d: 'd',
		vhd: 'vhd',
		v: 'v',
		asm: 'asm',
		clj: 'clj',
		groovy: 'groovy',
		dart: 'dart',
		kt: 'kt',
		js: 'js',
		jsx: 'jsx',
		vue: 'vue',
		ts: 'ts',
		tsx: 'tsx',
		py: 'py',
		html: 'html',
		css: 'css',
		json: 'json',
		go: 'go',
	},
	docTypes: {
		txt: 'txt',
		xlsx: 'xlsx',
		csv: 'csv',
		doc: 'doc',
		docx: 'docx',
		pdf: 'pdf',
		rtf: 'rtf',
		odt: 'odt',
	},
	imageDotTypes: {
		png: 'png',
		jpg: 'jpg',
		jpeg: 'jpeg',
		svg: 'svg',
		webp: 'webp',
	},
};
